plugins {
    id 'java'
    id 'application'
}

group = 'fr.deitycube'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'fr.deitycube.launcher.Launcher'
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.20.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}