buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.openjfx:javafx-plugin:0.1.0'
    }
}

plugins {
    id 'java'
    id 'application'
}

apply plugin: 'org.openjfx.javafxplugin'

group = 'fr.deitycube'
version = '1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'fr.deitycube.launcher.ui.LauncherApp'
}

javafx {
    version = '21.0.4'
    modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.20.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}